name: Deploy containers
on:
  push:
    branches:
    - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
      - uses: actions/checkout@v2
      - name: pull and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 34.155.254.188
          username: maalsi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          run: cd /srv/DjMarcelCiCd
          run: git pull origin main
          run: docker compose down
          run: docker compose up -d --build    