name: Deploy containers
on:
  push:
    branches:
    - main
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          ssh: |
            default=${{ env.SSH_PRIVATE_KEY }}
      - name: connect with ssh
        run: ssh maalsi@34.155.254.188

      - name: Clone repo
      - uses: actions/checkout@v4

      - name: cd repo
        run: cd /srv/DjMarcelCiCd

      - name: pull main
        run: git pull origin main

      - name: build container
        run: docker compose up -d --build

    # cd /srv/DjMarcelCiCd
    # git pull origin main
    # docker compose up -d --build