name: Deploy Containers

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Server
        run: |
          ssh -T maalsi@34.155.254.188 <<EOF
            cd /srv/DjMarcelCiCd
            git pull origin main
            docker-compose down --rmi all
            docker-compose up -d --build --force-recreate
          EOF